apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
     app: petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-app
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: petclinic-app    
    spec:
      containers:
      - name: petclinic-app
        image: preetham323/petclinicimg:latest
        ports:
         - name: app-port
           containerPort: 8080
        dnsPolicy: None
        dnsConfig:
        nameservers:
        - 172.20.0.10
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - us-east-2.compute.internal   
        env:
         - name: MYSQL_URL
           value: "jdbc:mysql://petclinicdb-service:3306/petclinic"
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               key: username
               name: petclinic-secret
         - name: MYSQL_PASSWORD
           valueFrom:
              secretKeyRef:
                key: password
                name: petclinic-secret
        
