apiVersion: v1
kind: Service
metadata:
  name: petclinicapp-service
spec:
  selector:
    app: petclinic-app
  ports:
  - port: 80
    targetPort: petclinicapp-port
    protocol: TCP
  type: LoadBalancer  
