apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-db
  labels:
    name: petclinic-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-db
  strategy: 
    type: Recreate    
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      containers:
      - name: petclinic-db
        image: mysql:8.0
        ports:
        - name: petclincdb-port
          containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               key: rootpasswd
               name: petclinic-secrets
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: petclinic-secrets
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: password
              name: petclinic-secrets     
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: petclinic-secrets     
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: persistent-storage      
      volumes: 
       - name: persistent-storage
         persistentVolumeClaim: 
           claimName: ebs-claim
         
         
        
