apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
     app: petclinic-app
spec:
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-app
        image: preetham323/petclinicimg:latest
        env:
         - name: MYSQL_URL
           value: jdbc:mysql://petclinic-db:3306/petclinicimg
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               key: username
               name: petclinic-secret
         - name: MYSQL_PASSWORD
           valueFrom:
              secretKeyRef:
                key: password
                name: petclinic-secret
        ports:
          containerPort: 8080
